# -*- coding: utf-8 -*-
"""DSPipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kK5iLYmd6NorXqdtQO0d-6cVvxhK91e7
"""

import pandas as pd

# Load the dataset
df = pd.read_csv('HR_comma_sep.csv')

# Look at the first few rows to understand the structure
print(df.head())

# Group the data by the 'left' column and find the average of all other numeric columns
# This shows us the average stats of employees who stayed (0) vs left (1)
print(df.groupby('left').mean(numeric_only=True))



import matplotlib.pyplot as plt

# 2. Impact of employee salaries on retention
pd.crosstab(df['salary'], df['left']).plot(kind='bar', figsize=(8,5))
plt.title('Employee Retention by Salary Level')
plt.xlabel('Salary Level')
plt.ylabel('Number of Employees')
plt.show()

# 3. Correlation between department and employee retention
pd.crosstab(df['Department'], df['left']).plot(kind='bar', figsize=(10,5))
plt.title('Employee Retention by Department')
plt.xlabel('Department')
plt.ylabel('Number of Employees')
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# Isolate the important variables
subdf = df[['satisfaction_level', 'average_montly_hours', 'promotion_last_5years', 'salary']]

# Convert the text 'salary' column into numerical dummy variables
salary_dummies = pd.get_dummies(subdf['salary'], prefix="salary")

# Combine our isolated data with the new dummy variables
df_with_dummies = pd.concat([subdf, salary_dummies], axis='columns')

# Drop the original text column as it's no longer needed
df_with_dummies.drop('salary', axis='columns', inplace=True)

# Define X (the features/input) and Y (the target/output)
X = df_with_dummies
y = df['left']

# Split the data into a training set (80%) and a testing set (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Build and train the model
model = LogisticRegression(max_iter=1000) # max_iter increased to ensure the math converges
model.fit(X_train, y_train)

# Measure the accuracy
accuracy = model.score(X_test, y_test)
print(f"Model Accuracy: {accuracy * 100:.2f}%")